port : "8080"

db : 
      username : "postgres"
      host : "localhost"
      port : "5432"
      dbname : "postgres"
      sslmode : "disable"

redis:
      host: "localhost"
      port: "6379"
      db: 0