port : "8080"

db : 
      username : "postgres" #"crm_user_actual"
      host : "dbgo.czcqgcwgs39c.eu-central-1.rds.amazonaws.com" #"postgres"
      port : "5432"
      dbname : "appdb" #"crm_db"
      sslmode : "disable"
redis:
      host: "localhost" #"redis"
      port: "6379"
      db: 0 